[package]
name = "near-state-parts-dump-check"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix.workspace = true
borsh.workspace = true
clap.workspace = true
reqwest = { version = "0.11.6", features = ["blocking", "json"]  }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon.workspace = true
cloud-storage.workspace = true
tracing.workspace = true
anyhow.workspace = true
near-primitives.workspace = true
nearcore.workspace = true
near-store.workspace = true
near-client.workspace = true
near-primitives-core.workspace = true
near-o11y.workspace = true
once_cell.workspace = true
tokio.workspace = true