name: Backward compatibility

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  merge_group:

jobs:
  backward_compat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
        cd pytest
        pip3 install --user -r requirements.txt
        pwd
        ls ..
        python3 tests/sanity/backward_compatible.py
        ls ../target/debug
