name: Build fuzz targets from master
on:
  push:
    branches:
      - master

jobs:
  build_fuzzers:
    runs-on: "ubuntu-20.04"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/968400232856/locations/global/workloadIdentityPools/project-identity-pool/providers/github-provider"
          service_account: "near-fuzzer-service-account@near-fuzzer.iam.gserviceaccount.com"

      - name: Installing nightly rust
        run: |
          rustup install nightly
          rustup default nightly

      - name: Set swap to 10G
        shell: bash
        run: |
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm $SWAP_FILE
          sudo fallocate -l 10G $SWAP_FILE
          sudo chmod 600 $SWAP_FILE
          sudo mkswap $SWAP_FILE
          sudo swapon $SWAP_FILE

      - name: Install cargo bolero subcommand crate
        run: cargo install cargo-bolero

      - run: rustup target add --toolchain nightly wasm32-unknown-unknown

      - name: "Set up GCP SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 416.0.0"

      - uses: actions/checkout@master

      - name: "Compile fuzzers and upload to GCS"
      - run: |
          NAME="nearcore-${{ github.ref_name }}-$(env TZ=Etc/UTC  date +"%Y%m%d%H%M%S")"
          cargo +nightly bolero build-clusterfuzz --all-features
          gsutil cp -Z target/fuzz/clusterfuzz.tar "gs://fuzzer_targets/${{ github.ref_name }}/$NAME.tar.gz"
